// Comprehensive suggestion database for tender creation forms
// Focused on 1-3 word phrases that are highly relevant and context-aware

import { capitalizeSentences } from './capitalize-helpers';

const PROJECT_TITLE_SUGGESTIONS_RAW = [
  // Web Development - Frontend
  "website development",
  "website redesign",
  "website optimization",
  "responsive website",
  "mobile-friendly website",
  "landing page",
  "e-commerce store",
  "online store",
  "shopping cart",
  "payment integration",
  "user interface",
  "user experience",
  "React developer",
  "Vue developer",
  "Angular developer",
  "frontend developer",
  "JavaScript developer",
  "TypeScript developer",
  "CSS expert",
  "HTML specialist",
  "web designer",
  "UI designer",
  "UX designer",
  "interface designer",

  // Web Development - Backend
  "backend developer",
  "full-stack developer",
  "API development",
  "REST API",
  "GraphQL API",
  "database design",
  "database optimization",
  "server setup",
  "cloud migration",
  "Node.js developer",
  "Python developer",
  "PHP developer",
  "Java developer",
  "Ruby developer",

  // CMS & Platforms
  "WordPress developer",
  "WordPress customization",
  "WordPress theme",
  "WordPress plugin",
  "Shopify expert",
  "Shopify store",
  "Shopify customization",
  "WooCommerce setup",
  "Magento developer",
  "Drupal developer",
  "Webflow designer",
  "Squarespace expert",

  // Design - Brand & Identity
  "logo design",
  "logo redesign",
  "brand identity",
  "brand guidelines",
  "brand strategy",
  "branding package",
  "visual identity",
  "corporate identity",
  "style guide",
  "color palette",
  "typography design",

  // Design - Graphics
  "graphic designer",
  "graphic design",
  "banner design",
  "poster design",
  "flyer design",
  "brochure design",
  "catalog design",
  "menu design",
  "infographic design",
  "presentation design",
  "slide deck",
  "pitch deck",
  "business cards",
  "letterhead design",
  "packaging design",
  "label design",

  // Design - Digital
  "social media",
  "Instagram posts",
  "Facebook graphics",
  "LinkedIn banners",
  "Twitter headers",
  "Pinterest pins",
  "YouTube thumbnails",
  "email templates",
  "newsletter design",
  "ad creatives",
  "display ads",
  "web banners",
  "app design",
  "mobile app",
  "icon design",
  "illustration services",

  // Video & Animation
  "video editing",
  "video production",
  "video editor",
  "promotional video",
  "explainer video",
  "product video",
  "corporate video",
  "training video",
  "tutorial video",
  "YouTube videos",
  "Instagram reels",
  "TikTok videos",
  "animation services",
  "motion graphics",
  "2D animation",
  "3D animation",
  "whiteboard animation",
  "character animation",
  "logo animation",
  "intro video",
  "outro video",
  "video thumbnail",
  "color grading",
  "sound design",
  "audio editing",

  // Marketing - Digital
  "digital marketing",
  "marketing strategy",
  "marketing campaign",
  "social media marketing",
  "social media manager",
  "content marketing",
  "email marketing",
  "influencer marketing",
  "affiliate marketing",
  "growth marketing",
  "performance marketing",

  // Marketing - Advertising
  "Facebook ads",
  "Instagram ads",
  "Google ads",
  "LinkedIn ads",
  "Twitter ads",
  "TikTok ads",
  "YouTube ads",
  "PPC campaign",
  "ad campaign",
  "advertising specialist",
  "media buyer",
  "ad copywriting",

  // Marketing - SEO & Content
  "SEO specialist",
  "SEO optimization",
  "keyword research",
  "link building",
  "local SEO",
  "technical SEO",
  "on-page SEO",
  "off-page SEO",
  "content writer",
  "blog writer",
  "copywriter needed",
  "article writing",
  "product descriptions",
  "website copywriting",

  // Writing & Content
  "content creation",
  "content strategy",
  "blog posts",
  "article writing",
  "copywriting services",
  "technical writing",
  "creative writing",
  "ghostwriting services",
  "proofreading services",
  "editing services",
  "translation services",
  "transcription services",
  "script writing",
  "screenplay writing",
  "press release",
  "case studies",
  "white papers",
  "ebooks writing",

  // Mobile Development
  "mobile app development",
  "iOS app",
  "Android app",
  "React Native",
  "Flutter developer",
  "app developer",
  "mobile developer",
  "cross-platform app",
  "native app",
  "hybrid app",

  // Data & Analytics
  "data analysis",
  "data visualization",
  "data scientist",
  "Excel expert",
  "Power BI",
  "Tableau expert",
  "Google Analytics",
  "data entry",
  "spreadsheet automation",
  "financial modeling",
  "market research",
  "business intelligence",

  // Business & Admin
  "virtual assistant",
  "administrative assistant",
  "project manager",
  "product manager",
  "business consultant",
  "operations manager",
  "customer support",
  "customer service",
  "sales representative",
  "lead generation",
  "email outreach",
  "cold calling",

  // Other Professional Services
  "accounting services",
  "bookkeeping services",
  "tax preparation",
  "legal services",
  "contract review",
  "HR consultant",
  "recruitment services",
  "training development",
  "course creation",
  "presentation expert",
];

const PROJECT_OBJECTIVE_SUGGESTIONS_RAW = [
  // Business Growth
  "increase sales",
  "boost revenue",
  "generate leads",
  "acquire customers",
  "expand market",
  "grow business",
  "scale operations",
  "improve profitability",
  "reduce costs",
  "increase efficiency",
  "maximize ROI",
  "drive growth",

  // Brand & Awareness
  "build brand",
  "increase awareness",
  "establish presence",
  "improve reputation",
  "enhance credibility",
  "strengthen brand",
  "create identity",
  "modernize brand",
  "rebrand company",
  "launch brand",
  "brand recognition",
  "market positioning",

  // Digital Presence
  "improve website",
  "increase traffic",
  "boost conversions",
  "enhance user experience",
  "optimize performance",
  "mobile optimization",
  "faster loading",
  "better navigation",
  "modernize website",
  "professional website",
  "online presence",
  "digital transformation",

  // Marketing & Engagement
  "engage customers",
  "reach audience",
  "build community",
  "increase engagement",
  "social media presence",
  "content strategy",
  "email campaigns",
  "lead nurturing",
  "customer retention",
  "brand loyalty",
  "thought leadership",
  "market education",

  // Product & Service
  "launch product",
  "introduce service",
  "promote offering",
  "showcase features",
  "demonstrate value",
  "attract buyers",
  "convert prospects",
  "drive adoption",
  "user onboarding",
  "product awareness",

  // Sales & Marketing
  "boost sales",
  "increase conversions",
  "improve CTR",
  "reduce bounce rate",
  "qualify leads",
  "sales funnel",
  "marketing automation",
  "campaign performance",
  "advertising ROI",
  "conversion optimization",

  // Customer Experience
  "improve satisfaction",
  "enhance experience",
  "customer delight",
  "support quality",
  "reduce churn",
  "increase retention",
  "loyalty program",
  "customer feedback",
  "service excellence",
  "user satisfaction",

  // Operations & Efficiency
  "streamline processes",
  "automate workflows",
  "improve productivity",
  "reduce manual work",
  "optimize operations",
  "increase capacity",
  "better collaboration",
  "team efficiency",
  "process improvement",
  "quality assurance",

  // Technology & Innovation
  "modernize systems",
  "upgrade technology",
  "implement solution",
  "digital innovation",
  "technical excellence",
  "secure platform",
  "scalable infrastructure",
  "cloud migration",
  "system integration",
  "API connectivity",

  // Competitive Advantage
  "competitive edge",
  "market leadership",
  "industry leader",
  "differentiate offering",
  "unique value",
  "stand out",
  "outperform competitors",
  "market share",
  "strategic positioning",
];

const KEY_DELIVERABLES_SUGGESTIONS_RAW = [
  // Web Development Deliverables
  "responsive design",
  "mobile responsive",
  "cross-browser compatibility",
  "website deployment",
  "domain setup",
  "hosting configuration",
  "SSL certificate",
  "security implementation",
  "performance optimization",
  "speed optimization",
  "SEO optimization",
  "Google Analytics",
  "contact form",
  "newsletter signup",
  "user registration",
  "login system",
  "user authentication",
  "password recovery",
  "admin dashboard",
  "content management",
  "database integration",
  "API integration",
  "payment gateway",
  "checkout system",
  "shopping cart",
  "product catalog",
  "search functionality",
  "filtering system",
  "image gallery",
  "photo slider",
  "video integration",
  "social media integration",
  "live chat",
  "email notifications",
  "automated emails",
  "custom forms",
  "interactive elements",
  "animations",
  "loading states",
  "error handling",
  "404 page",
  "privacy policy",
  "terms conditions",
  "cookie consent",
  "GDPR compliance",
  "accessibility features",
  "multilingual support",
  "backup system",
  "documentation",
  "training materials",
  "user guide",
  "technical support",
  "maintenance period",
  "bug fixes",
  "testing report",
  "quality assurance",

  // Design Deliverables
  "logo variations",
  "color variations",
  "final files",
  "source files",
  "vector files",
  "print files",
  "web formats",
  "high resolution",
  "transparent background",
  "brand guidelines",
  "style guide",
  "typography guide",
  "color palette",
  "brand assets",
  "social templates",
  "Instagram templates",
  "Facebook templates",
  "LinkedIn templates",
  "Twitter templates",
  "story templates",
  "post templates",
  "cover images",
  "profile pictures",
  "banner designs",
  "header images",
  "thumbnail templates",
  "email signatures",
  "business stationery",
  "letterhead design",
  "business cards",
  "envelope design",
  "presentation template",
  "slide master",
  "infographic design",
  "icon set",
  "custom illustrations",
  "stock photos",
  "image editing",
  "photo retouching",
  "background removal",
  "mockup designs",
  "packaging mockups",
  "product mockups",
  "print-ready files",
  "editable templates",
  "brand book",
  "usage guidelines",

  // Video & Content Deliverables
  "raw footage",
  "edited video",
  "final cut",
  "multiple formats",
  "HD quality",
  "4K quality",
  "aspect ratios",
  "vertical video",
  "square video",
  "landscape video",
  "intro animation",
  "outro animation",
  "lower thirds",
  "title graphics",
  "motion graphics",
  "animated elements",
  "transitions",
  "visual effects",
  "color correction",
  "color grading",
  "audio mixing",
  "sound effects",
  "background music",
  "voiceover recording",
  "subtitle files",
  "closed captions",
  "thumbnail design",
  "preview clips",
  "teaser videos",
  "behind-the-scenes",
  "blooper reel",
  "source files",
  "project files",

  // Marketing Deliverables
  "marketing strategy",
  "campaign plan",
  "content calendar",
  "posting schedule",
  "social media posts",
  "caption writing",
  "hashtag research",
  "ad creatives",
  "ad copy",
  "landing pages",
  "lead magnets",
  "email sequences",
  "drip campaigns",
  "newsletter templates",
  "blog posts",
  "article content",
  "keyword research",
  "competitor analysis",
  "market research",
  "target audience",
  "buyer personas",
  "customer journey",
  "funnel mapping",
  "conversion strategy",
  "analytics setup",
  "tracking implementation",
  "performance reports",
  "monthly reports",
  "analytics dashboard",
  "ROI analysis",
  "A/B testing",
  "optimization recommendations",
  "growth strategy",
  "campaign optimization",

  // Content Deliverables
  "blog articles",
  "SEO articles",
  "website content",
  "page content",
  "product descriptions",
  "category descriptions",
  "meta descriptions",
  "meta titles",
  "alt text",
  "heading tags",
  "internal linking",
  "content outline",
  "editorial calendar",
  "topic research",
  "fact checking",
  "proofreading",
  "editing",
  "formatting",
  "image sourcing",
  "content uploads",
  "CMS setup",
  "plagiarism check",
  "grammar check",
  "readability optimization",
  "tone consistency",

  // Technical Deliverables
  "source code",
  "code documentation",
  "API documentation",
  "technical specifications",
  "system architecture",
  "database schema",
  "wireframes",
  "mockups",
  "prototypes",
  "user flows",
  "sitemap",
  "flowcharts",
  "test cases",
  "test results",
  "bug reports",
  "deployment guide",
  "installation instructions",
  "configuration files",
  "environment setup",
  "version control",
  "Git repository",
  "code review",
  "security audit",
  "performance audit",
  "accessibility audit",
  "SEO audit",
  "compliance check",

  // Project Management Deliverables
  "project timeline",
  "milestone schedule",
  "task breakdown",
  "resource allocation",
  "budget breakdown",
  "progress updates",
  "weekly reports",
  "status meetings",
  "client presentations",
  "revision rounds",
  "feedback implementation",
  "change requests",
  "final approval",
  "handoff documentation",
  "training sessions",
  "knowledge transfer",
  "support documentation",
  "warranty period",
  "maintenance plan",
];

const PROJECT_DESCRIPTION_SUGGESTIONS_RAW = [
  // Opening Phrases
  "seeking experienced",
  "looking for",
  "need professional",
  "require expert",
  "searching for",
  "hiring talented",
  "want to",
  "planning to",
  "aiming to",
  "hoping to",
  "trying to",
  "working on",
  "developing",
  "creating",
  "building",
  "designing",
  "launching",
  "improving",
  "optimizing",
  "enhancing",
  "modernizing",
  "redesigning",
  "upgrading",
  "expanding",
  "growing",

  // Project Description
  "comprehensive solution",
  "professional service",
  "high-quality work",
  "quick turnaround",
  "attention to detail",
  "creative approach",
  "innovative design",
  "modern aesthetic",
  "clean design",
  "user-friendly",
  "intuitive interface",
  "seamless experience",
  "engaging content",
  "compelling copy",
  "persuasive messaging",
  "brand consistency",
  "visual appeal",
  "responsive layout",
  "mobile-first",
  "fast loading",
  "optimized performance",
  "scalable solution",
  "robust system",
  "secure platform",
  "reliable service",

  // Requirements
  "proven experience",
  "strong portfolio",
  "relevant expertise",
  "technical skills",
  "creative skills",
  "excellent communication",
  "timely delivery",
  "regular updates",
  "collaborative approach",
  "attention to deadlines",
  "quality focus",
  "detail-oriented",
  "proactive attitude",
  "problem-solving",
  "professional manner",
  "client-focused",
  "results-driven",
  "data-driven",
  "goal-oriented",
  "team player",
  "self-motivated",
  "reliable",
  "responsive",
  "flexible",
  "adaptable",

  // Project Scope
  "complete overhaul",
  "ground up",
  "from scratch",
  "existing project",
  "ongoing support",
  "one-time project",
  "long-term partnership",
  "short-term engagement",
  "immediate start",
  "flexible timeline",
  "tight deadline",
  "phased approach",
  "iterative process",
  "agile methodology",
  "collaborative process",
  "regular feedback",
  "multiple revisions",
  "unlimited revisions",
  "clear milestones",
  "defined deliverables",
  "specific requirements",
  "detailed brief",
  "comprehensive scope",

  // Tools & Technologies
  "latest technologies",
  "modern tools",
  "industry standards",
  "best practices",
  "proven methods",
  "cutting-edge",
  "state-of-the-art",
  "professional tools",
  "enterprise solutions",
  "cloud-based",
  "open-source",
  "proprietary",
  "custom-built",
  "off-the-shelf",
  "integrated systems",

  // Deliverables & Timeline
  "final deliverables",
  "source files",
  "working files",
  "editable files",
  "print-ready",
  "web-ready",
  "fully documented",
  "thoroughly tested",
  "quality assured",
  "ready to deploy",
  "ready to launch",
  "turnkey solution",
  "complete package",
  "end-to-end",
  "start to finish",
  "concept to completion",
  "timely delivery",
  "on schedule",
  "within budget",
  "within timeline",
];

// Apply proper capitalization to all suggestions
export const PROJECT_TITLE_SUGGESTIONS = capitalizeSentences(PROJECT_TITLE_SUGGESTIONS_RAW);
export const PROJECT_OBJECTIVE_SUGGESTIONS = capitalizeSentences(PROJECT_OBJECTIVE_SUGGESTIONS_RAW);
export const KEY_DELIVERABLES_SUGGESTIONS = capitalizeSentences(KEY_DELIVERABLES_SUGGESTIONS_RAW);
export const PROJECT_DESCRIPTION_SUGGESTIONS = capitalizeSentences(PROJECT_DESCRIPTION_SUGGESTIONS_RAW);

// Helper function to get context-aware suggestions
export function getSuggestions(context: "title" | "objective" | "deliverable" | "description"): string[] {
  switch (context) {
    case "title":
      return PROJECT_TITLE_SUGGESTIONS;
    case "objective":
      return PROJECT_OBJECTIVE_SUGGESTIONS;
    case "deliverable":
      return KEY_DELIVERABLES_SUGGESTIONS;
    case "description":
      return PROJECT_DESCRIPTION_SUGGESTIONS;
    default:
      return [];
  }
}
